name: Deployment Flow

on:
  workflow_call:
    inputs:
      env_tag:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOCKER_IMAGE_REPOSITORY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DEPLOYMENT_FILE:
        required: true
      KUBE_CA:
        required: true
      KUBE_TOKEN:
        required: true
      KUBE_CLUSTER:
        required: true
      KUBE_SERVER:
        required: true
      GCP_STORAGE_KEY:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }} env
    runs-on: ubuntu-latest
    container: google/cloud-sdk:latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to ${{ inputs.environment }}
        run: |
          export IMAGE_NAME=asia.gcr.io/$DOCKER_IMAGE_REPOSITORY/$ENV_TAG/$REPOSITORY_NAME:$GITHUB_SHA
          docker build -t $IMAGE_NAME --build-arg ENV_TAG=$ENV_TAG .
          docker login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD" https://asia.gcr.io
          docker push $IMAGE_NAME
          sed -i "s|{{image}}|$IMAGE_NAME|g" $DEPLOYMENT_FILE
          echo $KUBE_TOKEN | base64 --decode > ./kube_token
          echo $KUBE_CA | base64 --decode > ./kube_ca
          kubectl config set-cluster $KUBE_CLUSTER --server=$KUBE_SERVER --certificate-authority="$(pwd)/kube_ca"
          kubectl config set-credentials github --token="$(cat ./kube_token)"
          kubectl config set-context development --cluster=$KUBE_CLUSTER --user=github
          kubectl config use-context development
          kubectl apply -f $DEPLOYMENT_FILE
        env:
          REPOSITORY_NAME: nest_api_gateway
          ENV_TAG: ${{ inputs.env_tag }}
          DOCKER_IMAGE_REPOSITORY: ${{ secrets.DOCKER_IMAGE_REPOSITORY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DEPLOYMENT_FILE: ${{ secrets.DEPLOYMENT_FILE}}
          KUBE_CA: ${{ secrets.KUBE_CA }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
